# NumPy 

NumPy (o Numpy) es una libreria de Algebra Linear para Python, la razon por la que es tan importante para Ciencia de Datos con Python es que casi todas las librerias del ecosistema del trabajo con datos recaen en Numpy como uno de sus bloques principales.

Ademas Numpy es increiblemente rapido, es mas conveniente usar arrays de Numpy en ves de listas en Python.


## Usando NumPy

Lo importamos como cualquier otro modulo

In [1]:
import numpy as np

Numpy tiene muchas funciones y capacidades. No las vamos a ver todas sino que nos vamos a enfocar en los aspectos mas importantes de Numpy: vectores, arreglos, matrices y generacion de numeros.

Empecemos viendo los arreglos

### Arreglos de Numpy 

Es el tipo de dato principal de Numpy. Principalmente podemos encontrar arreglos denominados vectores (1 dimension) o matrices ( 2 dimensiones).

Sin embargo con Numpy podemos trabajar con muchas dimensiones.



### Creamos arreglos

#### A traves de listas

Podemos crear arreglos directamente convirtiendo una lista en un arreglo.


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
print(my_list)

[1, 2, 3]


In [5]:
print(np.array(my_list))

[1 2 3]


In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### A traves de funciones propias de Numpy

Hay varias maneras de crear arreglos directamente con Numpy

#### arange

Nos devuelve un arreglo como si usaramos la funcion range.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones

Genera arreglos llenos de ceros o unos

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [26]:
# podemos crear un arreglo de dos dimensiones
# hay que pasar como parametro una tupla con tantos elementos como dimensiones tenga el arreglo, y cada elemento va a indicar
# la cantidad de valores que hay en cada dimension respectivamente.

# a esta tupla se la denomina shape (forma) del arreglo

np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [18]:
np.zeros((5,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

####  full

La funcion full nos permitira crear un arreglo de las dimensiones especificadas rellenado con el valor especificado.

In [17]:
np.full((4,2),50)

array([[50, 50],
       [50, 50],
       [50, 50],
       [50, 50]])

#### linspace

Nos devuelve un arreglo con los valores espaciados equitativamente entre dos limites.


In [29]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

#### eye and identity

Crean la matriz de identidad.

Es aquella matriz llena de ceros excepto por su diagonal que va a poseer unos.

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# dif entre eye e identity

np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

### Random 

Numpy tambien tiene formas de crear arreglos aleatorios.

#### rand
Crea un arreglo del tamano especificado y lo rellena con numeros aleatorios entre 0 y 1 (sin incluir al 1)

In [47]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [46]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

#### randint

Devuelve un arreglo con numeros enteros aleatorios entre un limite inferior (incluido) y un limite superior (excluido)

In [50]:
np.random.randint(1,100)

44

In [51]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Atributos y metodos de los arreglos

Veamos algunos atributos y metodos interesantes de los arreglos:

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([45, 46, 48, 33, 49, 30,  1, 10,  6, 29])

### Reshape

Nos devuelve un array conteniendo los mismos valores pero con una nueva forma(shape)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estos metodos nos permiten encontrar los valores maximos y minimos. Asi como encontrar el indice (ubicacion) de estos valores.


In [64]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [61]:
ranarr.max()

49

In [62]:
ranarr.argmax()

4

In [63]:
ranarr.min()

2

In [60]:
ranarr.argmin()

5

### Shape

Es un atributo de los arreglos, nos devuelve la tupla indicando cuantos elementos tenemos en cada dimension.

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Veamos que tiene de diferente esto con un vector
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### transpose

Es un metodo que va a transponer la matriz, es decir, va a convertir a las filas en columnas y viceversa

In [29]:
arr = np.arange(1,101)
arr = arr.reshape((10,10))

In [30]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### ndim

Es un atributo y nos indica la cantidad de dimensions que tiene nuestro arreglo

In [26]:
arr.ndim

1

### dtype

Es un atributo y nos indica el tipo de dato dentro del arreglo.

In [27]:
arr.dtype

dtype('int32')