# NumPy Indexing

Vamos a ver como seleccionar elementos, o grupos de elementos de un arreglo.

In [1]:
import numpy as np

In [2]:
#Creamos un arreglo 
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Indexing con []
La manera mas simple de agarrar los elementos de un array es de manera muy similar a el indexing en las listas.


In [14]:
#Agarramos el valor en esa posicion especifica
arr[8]

8

In [15]:
#Slicing
arr[1:5]

array([1, 2, 3, 4])

In [16]:
#Get values in a range
arr[:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Los arreglos de Numpy difieren de las listas en el sentido que estos tienen la propiedad de broadcasting, es decir poder hacer una asignacion como la siguiente.

In [17]:
#Establecer un valor a un conjunto de elementos (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
# Resetiemos los valores del array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#Supongamos que agarramos una porcion del array
slice_of_arr = arr[0:6]

#Mostrar
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
#Cambiamos los valores de esa porcion
slice_of_arr[:]=99

#Mostrar
slice_of_arr

array([99, 99, 99, 99, 99, 99])

**Pero ahora notemos como el cambio tambien ocurre en el arreglo original !**


In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Esto es porque al hacer el slicing, los datos no son copiados sino que son una vista del arreglo original, esto evita problemas de memoria al trabajar con una gran cantidad de datos.



In [13]:
#Para tener una copia necesitamos ser explicitos
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr = arr[0:6].copy()
slice_of_arr[:]=11


arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr

array([11, 11, 11, 11, 11, 11])

## Indexing arreglos 2D (matrices)

El formato general es **arr_2d[fila][col]** o **arr_2d[fila,col]**. Recomiendo usar la segunda notacion para darle mayor claridad a que estamos trabajando con arreglos.


In [24]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Mostrar
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
#Indexing fila
arr_2d[1]


array([20, 25, 30])

In [26]:

# Agarrando un unico elemento con sintaxis 1
arr_2d[1][0]

20

In [27]:
# # Agarrando un unico elemento con sintaxis 2
arr_2d[1,0]

20

In [28]:
# slicing

# Agarremos 4 elementos, los 4 de la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
# Agarremos 4 elementos, los 4 de la esquina inferior izquierda
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

### Fancy Indexing

Es un metodo nuevo de indexing y nos permite seleccionar filas enteras o columnas sin un orden en particular.


In [6]:
#Creamos una matriz de 10x10
arr2d = np.zeros((10,10))

In [7]:
#Longitud del arreglo
arr_length = arr2d.shape[1]

In [8]:
#Modificamos el arreglo

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing nos permite lo siguiente

In [33]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [34]:
#En cualquier orden
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [38]:
#Modificamos el arreglo

for i in range(arr_length):
    arr2d[i] = np.linspace(i,i+1,10,False)
    
arr2d

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

In [39]:
# si queremos agarrar las columnas
arr2d[:,[6,4,2,7]]

array([[0.6, 0.4, 0.2, 0.7],
       [1.6, 1.4, 1.2, 1.7],
       [2.6, 2.4, 2.2, 2.7],
       [3.6, 3.4, 3.2, 3.7],
       [4.6, 4.4, 4.2, 4.7],
       [5.6, 5.4, 5.2, 5.7],
       [6.6, 6.4, 6.2, 6.7],
       [7.6, 7.4, 7.2, 7.7],
       [8.6, 8.4, 8.2, 8.7],
       [9.6, 9.4, 9.2, 9.7]])

In [40]:
# si queremos agarrar elementos en particular (interseccion entre filas y columnas)

arr2d[[6,4,2,7],[6,4,2,7]]

array([6.6, 4.4, 2.2, 7.7])

In [41]:
arr2d[[1,5,8,0],[6,4,2,7]]

array([1.6, 5.4, 8.2, 0.7])

En un principio acostumbrarse al indexing de arreglos puede ser confuso, pero con la practica todo se aprende.

## Seleccion de valores (filtrado)

Aqui es donde se usa el famoso termino de mascaras, veamos a que nos referimos.

In [43]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
bool_arr = arr>4

In [46]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Vamos a repasar este concepto en mas profundidad cuando veamos Pandas, asiq no se preocupen si aun no queda del todo claro.