In [7]:
import numpy as np

Debes utilizar numpy
1. ingresa por teclado la cantidad filas
2. ingresa por teclado la cantidad columnas
3. crea un arreglo de numpy de dimension filas columnas con elementos de tipo float.
4. rellena el array con 5.1
5. imprime shape, tipo y el arreglo

In [ ]:
import numpy as np
filas = int(input())
col = int(input())
arreglo = np.ones((filas,col))*5.1
print(arreglo.ndim, arreglo.dtype)
print(arreglo)

Debes utilizar numpy
1. ingresa por teclado la cantidad n de elementos
2. crea un arreglo de numpy de una dimension con una cantidad n de elementos rellena de ceros de tipo int.
3. imprime shape, tipo y el arreglo

In [17]:
n = int(input())
arreglo = np.zeros(n,int)
print(arreglo.shape, arreglo.dtype)
print(arreglo)

5
(5,) int32
[0 0 0 0 0]


Ingrese al programa un numero entero 'n'. 

Crea un array de n elementos enteros consecutivos (de 0 a n).

Reformatea el array a un array cuadrado (reshape)

Imprima las dimensiones (ndim) , el tipo del array y el array 

In [4]:
from math import sqrt
import numpy as np

n = int(input())

arreglo = np.arange(0,n)
n = int(sqrt(n))
arreglo = arreglo.reshape(n,n)
print(arreglo.shape, arreglo.dtype)
print(arreglo)

16
(4, 4) int32
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Debes utilizar numpy (empty)
1. ingresa por teclado la cantidad filas
2. ingresa por teclado la cantidad columnas

3. crea un arreglo de numpy de dimension filas columnas con elementos de tipo float.
4. rellena el array con -.5
5. imprime shape, tipo y el arreglo

In [ ]:
filas = int(input())
col = int(input())

arreglo = np.ones((filas,col),float)*-.5
print(arreglo.shape, arreglo.dtype)
print(arreglo)

Debes utilizar numpy (transpose)
1. recibes un arreglo A con la rutina precargada
2. almacena en B la transpuesta de A
3. almacena en C el producto de A.B
4. imprime size de C
5. imprime C

In [ ]:
import numpy as np

fi=int(input())
co=int(input())
A=np.ones((fi,co))
for i in range(fi):
    for j in range(co):
        A[i,j]=float(input())
        
B = np.transpose(A)
C = A.dot(B)

print(C.size)
print(C)

Debes utilizar numpy (cumprod)
1. recibes un arreglo A con la rutina precargada
2. imprime cumprod valor de A
5. imprime los cumprod por fila de A
4. imprime los cumprod por columna de A


https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html

In [ ]:
# boludear un poco con este tema para entenderlo

In [ ]:
import numpy as np

fi=int(input())
co=int(input())
A=np.zeros((fi,co))
for i in range(fi):
    for j in range(co):
        A[i,j]=float(input())
        
print(np.cumprod(A))
#por filas
print(np.cumprod(A,axis=0))
# por columnas
print(np.cumprod(A,axis=1))


Debes utilizar numpy (full)
1 - ingresa por teclado la cantidad filas
2 - ingresa por teclado la cantidad columnas

3 - crea un arreglo de numpy de dimension filas columnas con elementos de tipo float.
4 - rellena el array con -3.2
5 - imprime ndim, tipo y el arreglo

In [ ]:
import numpy as np

fi = int(input())
co = int(input())

arreglo = np.full((fi,co),-3.2, dtype=float)
print(arreglo.ndim,arreglo.dtype)
print(arreglo)

Debes utilizar numpy (eye)
1 - ingresa por teclado la cantidad filas
2 - ingresa por teclado la cantidad columnas

3 - crea un arreglo m de numpy de dimension filas columnas con elementos de tipo i2.
4 - opera el array m - con -3.2
5 - imprime ndim, tipo y el arreglo

In [ ]:
import numpy as np

fi = int(input())
co = int(input())

a = np.eye(fi,co,dtype=np.float64) - (-3.2)

print(a.ndim,a.dtype)
print(a)

Debes utilizar numpy (cumsum)
1 - recibes un arreglo A con la rutina precargada
2 - imprime cumsum valor de A
5 - imprime los cumsum por fila de A
4 - imprime los cumsum por columna de A

In [ ]:
import numpy as np
fi=int(input())
co=int(input())
A=np.empty((fi,co))
for i in range(fi):
    for j in range(co):
        A[i,j]=float(input())
        
print(np.cumsum(A))
#por filas
print(np.cumsum(A,axis=0))
# por columnas
print(np.cumsum(A,axis=1))

Debes utilizar numpy (min)
1 - recibes un arreglo A con la rutina precargada
2 - imprime min valor de A
5 - imprime los min por fila de A
4 - imprime los min por columna de A

In [ ]:
import numpy as np
fi=int(input())
co=int(input())
A=np.empty((fi,co))
for i in range(fi):
    for j in range(co):
        A[i,j]=float(input())
        
        
print(np.min(A))
#por filas
print(np.min(A,axis=0))
# por columnas
print(np.min(A,axis=1))

Debes utilizar numpy (arange y tan)
1 - ingresa por teclado la cantidad filas
2 - ingresa por teclado la cantidad columnas

3 - crea un arreglo m de numpy de dimension filas columnas con elementos de tipo i2.
4 - aplica al array m la funcion tan y multiplica por 5.9
5 - imprime shape y el arreglo

In [ ]:
import numpy as np

fi = int(input())
co = int(input())

a = np.arange(fi,co,dtype=np.int16)
a = np.tan(a) * 5.9

print(a.ndim,a.dtype)
print(a)