# Ejercicios sobre lo aprendido

## Suban este notebook resuelto al drive con la nomenclatura nombre_apellido_TP_5

Debes utilizar numpy
1. ingresa por teclado la cantidad filas
2. ingresa por teclado la cantidad columnas
3. crea un arreglo de numpy de dimension filas columnas con elementos de tipo float.
4. rellena el array con 10.5
5. imprime shape, tipo y el arreglo

In [ ]:
import numpy as np
filas = int(input())
col = int(input())
arreglo = np.ones((filas,col))*5.1
print(arreglo.ndim, arreglo.dtype)
print(arreglo)

Ingrese al programa un numero entero 'n'. 

Crea un array de n elementos enteros consecutivos (de 0 a n).

Reformatea el array a un array cuadrado (reshape)

Imprima las dimensiones (ndim) , el tipo del array y el array 

In [4]:
from math import sqrt
import numpy as np

n = int(input())

arreglo = np.arange(0,n)
n = int(sqrt(n))
arreglo = arreglo.reshape(n,n)
print(arreglo.shape, arreglo.dtype)
print(arreglo)

16
(4, 4) int32
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Debes utilizar numpy 
1. crear una matriz de 3x3 con numeros enteros aleatorios (entre 1 y 50)
2. almacena en B la transpuesta de A
3. almacena en C el producto de A*B y en D la suma de A+B
4. imprime size de C y D
5. imprime shape de C y D
5. imprime C y D

In [4]:
import numpy as np

A = np.random.randint(1,50,(3,3))

B = np.transpose(A)

C = A*B

D = A+B

print(C.size, D.size)
print("")
print(C.shape, D.shape)
print("")
print(C)
print("")
print(D)

9 9

(3, 3) (3, 3)

[[  49 2256   48]
 [2256  900   70]
 [  48   70 1849]]

[[14 95 16]
 [95 60 17]
 [16 17 86]]


Debes utilizar numpy 
1. crear una matriz A de 5x5 con numeros igualmente espaciados (entre 1 y 2.5 ) e imprimirla
2. imprime la suma de todos los elementos de A
3. imprime la suma de todos los elementos de cada fila de A
4. imprime la suma de todos los elementos de cada columna de A
5. imprime la suma acumulada de todo A



In [11]:
import numpy as np

A = np.linspace(1,2.5,25)
A = A.reshape((5,5))      

print(A.sum())

print(A.sum(axis=0))

print(A.sum(axis=1))

print(np.cumsum(A))


43.75
[8.125  8.4375 8.75   9.0625 9.375 ]
[ 5.625   7.1875  8.75   10.3125 11.875 ]
[ 1.      2.0625  3.1875  4.375   5.625   6.9375  8.3125  9.75   11.25
 12.8125 14.4375 16.125  17.875  19.6875 21.5625 23.5    25.5    27.5625
 29.6875 31.875  34.125  36.4375 38.8125 41.25   43.75  ]


## Suban este notebook resuelto al drive con la nomenclatura nombre_apellido_TP_5